// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PushPresenceService.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_PushPresenceService_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_PushPresenceService_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_PushPresenceService_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_PushPresenceService_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_PushPresenceService_2eproto;
namespace PushPresenceService {
class PrescencePushData;
class PrescencePushDataDefaultTypeInternal;
extern PrescencePushDataDefaultTypeInternal _PrescencePushData_default_instance_;
}  // namespace PushPresenceService
PROTOBUF_NAMESPACE_OPEN
template<> ::PushPresenceService::PrescencePushData* Arena::CreateMaybeMessage<::PushPresenceService::PrescencePushData>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace PushPresenceService {

// ===================================================================

class PrescencePushData PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:PushPresenceService.PrescencePushData) */ {
 public:
  inline PrescencePushData() : PrescencePushData(nullptr) {};
  virtual ~PrescencePushData();

  PrescencePushData(const PrescencePushData& from);
  PrescencePushData(PrescencePushData&& from) noexcept
    : PrescencePushData() {
    *this = ::std::move(from);
  }

  inline PrescencePushData& operator=(const PrescencePushData& from) {
    CopyFrom(from);
    return *this;
  }
  inline PrescencePushData& operator=(PrescencePushData&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const PrescencePushData& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PrescencePushData* internal_default_instance() {
    return reinterpret_cast<const PrescencePushData*>(
               &_PrescencePushData_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(PrescencePushData& a, PrescencePushData& b) {
    a.Swap(&b);
  }
  inline void Swap(PrescencePushData* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PrescencePushData* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline PrescencePushData* New() const final {
    return CreateMaybeMessage<PrescencePushData>(nullptr);
  }

  PrescencePushData* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<PrescencePushData>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const PrescencePushData& from);
  void MergeFrom(const PrescencePushData& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PrescencePushData* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "PushPresenceService.PrescencePushData";
  }
  protected:
  explicit PrescencePushData(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_PushPresenceService_2eproto);
    return ::descriptor_table_PushPresenceService_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kKukuFieldNumber = 3,
    kVersionFieldNumber = 1,
    kDummyFieldNumber = 2,
  };
  // string kuku = 3;
  void clear_kuku();
  const std::string& kuku() const;
  void set_kuku(const std::string& value);
  void set_kuku(std::string&& value);
  void set_kuku(const char* value);
  void set_kuku(const char* value, size_t size);
  std::string* mutable_kuku();
  std::string* release_kuku();
  void set_allocated_kuku(std::string* kuku);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_kuku();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_kuku(
      std::string* kuku);
  private:
  const std::string& _internal_kuku() const;
  void _internal_set_kuku(const std::string& value);
  std::string* _internal_mutable_kuku();
  public:

  // int32 version = 1;
  void clear_version();
  ::PROTOBUF_NAMESPACE_ID::int32 version() const;
  void set_version(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_version() const;
  void _internal_set_version(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 dummy = 2;
  void clear_dummy();
  ::PROTOBUF_NAMESPACE_ID::int32 dummy() const;
  void set_dummy(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_dummy() const;
  void _internal_set_dummy(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:PushPresenceService.PrescencePushData)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr kuku_;
  ::PROTOBUF_NAMESPACE_ID::int32 version_;
  ::PROTOBUF_NAMESPACE_ID::int32 dummy_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_PushPresenceService_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// PrescencePushData

// int32 version = 1;
inline void PrescencePushData::clear_version() {
  version_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 PrescencePushData::_internal_version() const {
  return version_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 PrescencePushData::version() const {
  // @@protoc_insertion_point(field_get:PushPresenceService.PrescencePushData.version)
  return _internal_version();
}
inline void PrescencePushData::_internal_set_version(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  version_ = value;
}
inline void PrescencePushData::set_version(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_version(value);
  // @@protoc_insertion_point(field_set:PushPresenceService.PrescencePushData.version)
}

// int32 dummy = 2;
inline void PrescencePushData::clear_dummy() {
  dummy_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 PrescencePushData::_internal_dummy() const {
  return dummy_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 PrescencePushData::dummy() const {
  // @@protoc_insertion_point(field_get:PushPresenceService.PrescencePushData.dummy)
  return _internal_dummy();
}
inline void PrescencePushData::_internal_set_dummy(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  dummy_ = value;
}
inline void PrescencePushData::set_dummy(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_dummy(value);
  // @@protoc_insertion_point(field_set:PushPresenceService.PrescencePushData.dummy)
}

// string kuku = 3;
inline void PrescencePushData::clear_kuku() {
  kuku_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& PrescencePushData::kuku() const {
  // @@protoc_insertion_point(field_get:PushPresenceService.PrescencePushData.kuku)
  return _internal_kuku();
}
inline void PrescencePushData::set_kuku(const std::string& value) {
  _internal_set_kuku(value);
  // @@protoc_insertion_point(field_set:PushPresenceService.PrescencePushData.kuku)
}
inline std::string* PrescencePushData::mutable_kuku() {
  // @@protoc_insertion_point(field_mutable:PushPresenceService.PrescencePushData.kuku)
  return _internal_mutable_kuku();
}
inline const std::string& PrescencePushData::_internal_kuku() const {
  return kuku_.Get();
}
inline void PrescencePushData::_internal_set_kuku(const std::string& value) {
  
  kuku_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void PrescencePushData::set_kuku(std::string&& value) {
  
  kuku_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:PushPresenceService.PrescencePushData.kuku)
}
inline void PrescencePushData::set_kuku(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  kuku_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:PushPresenceService.PrescencePushData.kuku)
}
inline void PrescencePushData::set_kuku(const char* value,
    size_t size) {
  
  kuku_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:PushPresenceService.PrescencePushData.kuku)
}
inline std::string* PrescencePushData::_internal_mutable_kuku() {
  
  return kuku_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* PrescencePushData::release_kuku() {
  // @@protoc_insertion_point(field_release:PushPresenceService.PrescencePushData.kuku)
  return kuku_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void PrescencePushData::set_allocated_kuku(std::string* kuku) {
  if (kuku != nullptr) {
    
  } else {
    
  }
  kuku_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), kuku,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:PushPresenceService.PrescencePushData.kuku)
}
inline std::string* PrescencePushData::unsafe_arena_release_kuku() {
  // @@protoc_insertion_point(field_unsafe_arena_release:PushPresenceService.PrescencePushData.kuku)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return kuku_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void PrescencePushData::unsafe_arena_set_allocated_kuku(
    std::string* kuku) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (kuku != nullptr) {
    
  } else {
    
  }
  kuku_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      kuku, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:PushPresenceService.PrescencePushData.kuku)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace PushPresenceService

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_PushPresenceService_2eproto
